---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: deployment-azuredisk-win
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      name: deployment-azuredisk-win
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: busybox-azuredisk
          image: mcr.microsoft.com/windows/servercore:ltsc2022
          command:
            - "powershell.exe"
            - "-Command"
            - "while (1) { Add-Content -Encoding Ascii C:\\mnt\\azuredisk\\data.txt $(Get-Date -Format u); sleep 1 }"
          volumeMounts:
            - name: azuredisk
              mountPath: "/mnt/azuredisk"
              readOnly: false
      volumes:
        - name: azuredisk
          persistentVolumeClaim:
            claimName: pvc-azuredisk
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
