---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_LRS  # available values: StandardSSD_LRS, StandardSSD_ZRS, Premium_LRS, Premium_ZRS, etc.
reclaimPolicy: Delete
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.disk.csi.azure.com/zone
        values:
          - eastus2-1
---
