apiVersion: v1
entries:
  azuredisk-csi-driver:
  - apiVersion: v1
    appVersion: latest-v2
    created: "2023-10-18T11:06:10.888215653Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: b261d370dfb8bde4d15d6285d57c87369d9c66d12b92c8c6ad2b85495365759a
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.7.tgz
    version: v2.0.0-beta.7
  - apiVersion: v1
    appVersion: v2.0.0-beta.6
    created: "2023-10-18T11:06:10.937390457Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 0e7280d2bcd752668c4439078ffdfc4567ac97af97d8baa07c322b99c34fb741
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v2.0.0-beta.6/azuredisk-csi-driver-v2.0.0-beta.6.tgz
    version: v2.0.0-beta.6
  - apiVersion: v1
    appVersion: v2.0.0-beta.5
    created: "2023-10-18T11:06:10.935732093Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 10189dd78863d24c9572c468e0d81b8781f83625118e6b205ee65e157aab0602
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v2.0.0-beta.5/azuredisk-csi-driver-v2.0.0-beta.5.tgz
    version: v2.0.0-beta.5
  - apiVersion: v1
    appVersion: v2.0.0-beta.4
    created: "2023-10-18T11:06:10.933385409Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: b38901738bb600ff55cc91e1efb45c84a3a601bb815908a348df793960cd7122
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v2.0.0-beta.4/azuredisk-csi-driver-v2.0.0-beta.4.tgz
    version: v2.0.0-beta.4
  - apiVersion: v1
    appVersion: v2.0.0-beta.3
    created: "2023-10-18T11:06:10.932003995Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: ddfe774c7b2326ff61c71a7e6fbfe687e97f06b6a8cc5e87c0b50ac0f320c7fe
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v2.0.0-beta.3/azuredisk-csi-driver-v2.0.0-beta.3.tgz
    version: v2.0.0-beta.3
  - apiVersion: v1
    appVersion: v2.0.0-beta.2
    created: "2023-10-18T11:06:10.930769355Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 7c1b8159465e7642b7460ec8e4e2a2965be11e8abb8310d86d9487676adb6adc
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v2.0.0-beta.2/azuredisk-csi-driver-v2.0.0-beta.2.tgz
    version: v2.0.0-beta.2
  - apiVersion: v1
    appVersion: v2.0.0-beta.1
    created: "2023-10-18T11:06:10.929516868Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: f327e1205e7197cf87693012848e2fd76a213c7852ac57a50753ba9e41207612
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v2.0.0-beta.1/azuredisk-csi-driver-v2.0.0-beta.1.tgz
    version: v2.0.0-beta.1
  - apiVersion: v1
    appVersion: v2.0.0-alpha.1
    created: "2023-10-18T11:06:10.927277251Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: a00216ca8bdd4550f01071c0a57e7cf49f20b4915164ec6c785d2b5e51893870
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v2.0.0-alpha.1/azuredisk-csi-driver-v2.0.0-alpha.1.tgz
    version: v2.0.0-alpha.1
  - apiVersion: v1
    appVersion: v1.26.7
    created: "2023-10-18T11:06:10.886486013Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 41b383fe1d7f62112b91831bea1ad0c15027e0fdbc090e02d2e014e8bb5ffbe2
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/latest/azuredisk-csi-driver-v1.26.7.tgz
    version: v1.26.7
  - apiVersion: v1
    appVersion: v1.26.7
    created: "2023-10-18T11:06:10.919453707Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 8796e69d622aaef119bf87047d1d7ed699e88119d48655590813ec5a38a3ccab
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.26.7/azuredisk-csi-driver-v1.26.7.tgz
    version: v1.26.7
  - apiVersion: v1
    appVersion: v1.26.6
    created: "2023-10-18T11:06:10.918418074Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 277051eba7872783d34d9b8ba7bd606f3161afe571523eaabfa8b400491010c9
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.26.6/azuredisk-csi-driver-v1.26.6.tgz
    version: v1.26.6
  - apiVersion: v1
    appVersion: v1.26.5
    created: "2023-10-18T11:06:10.91626049Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 57ca0a3b61b2802fe3f811b91d0e38372a4ec32d99cf9298419550a51074da71
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.26.5/azuredisk-csi-driver-v1.26.5.tgz
    version: v1.26.5
  - apiVersion: v1
    appVersion: v1.26.4
    created: "2023-10-18T11:06:10.915249177Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 8d562f0dc2e3b480a77f0012676dd1377b6abb1de7254d8a267634102ce06e55
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.26.4/azuredisk-csi-driver-v1.26.4.tgz
    version: v1.26.4
  - apiVersion: v1
    appVersion: v1.26.3
    created: "2023-10-18T11:06:10.91424165Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: b807a4d4517aedba934d33327e2aea5661de70d7348c14f3646859fb0129ed74
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.26.3/azuredisk-csi-driver-v1.26.3.tgz
    version: v1.26.3
  - apiVersion: v1
    appVersion: v1.26.2
    created: "2023-10-18T11:06:10.913216763Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 27f51976ddfa48b5eaf2f3a958d4af3c34718ff552d7c5a8c6635d8657fe587e
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.26.2/azuredisk-csi-driver-v1.26.2.tgz
    version: v1.26.2
  - apiVersion: v1
    appVersion: v1.26.1
    created: "2023-10-18T11:06:10.912141879Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 280ae607fbbec8282e785c9762de294e92f8c43babd41fd20b93e7066d590639
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.26.1/azuredisk-csi-driver-v1.26.1.tgz
    version: v1.26.1
  - apiVersion: v1
    appVersion: v1.26.0
    created: "2023-10-18T11:06:10.91002506Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 7d7856926b29ee87a3e69b12df620c4460b3d15053fdefd5b23aeba01286ef52
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.26.0/azuredisk-csi-driver-v1.26.0.tgz
    version: v1.26.0
  - apiVersion: v1
    appVersion: v1.25.0
    created: "2023-10-18T11:06:10.908990125Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: cc1a78eb68d741382945252fdc86dc38fc903bcc7448eef5753a1e663e4e6e3c
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.25.0/azuredisk-csi-driver-v1.25.0.tgz
    version: v1.25.0
  - apiVersion: v1
    appVersion: v1.24.0
    created: "2023-10-18T11:06:10.907952322Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 8f4a2048cd3d8ef128e533c43c5b68464989e28949658010599d466b2ccb1b58
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.24.0/azuredisk-csi-driver-v1.24.0.tgz
    version: v1.24.0
  - apiVersion: v1
    appVersion: v1.23.0
    created: "2023-10-18T11:06:10.906942769Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 4347271a297c6c95e10c4a880a08453c22839c95ad7db232d2d8fc38e926b385
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.23.0/azuredisk-csi-driver-v1.23.0.tgz
    version: v1.23.0
  - apiVersion: v1
    appVersion: v1.22.0
    created: "2023-10-18T11:06:10.905852272Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: fc7adc9ddb406356bee117d3ba5c360408b4ee9a7decc30d34fe310d0cdd6aef
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.22.0/azuredisk-csi-driver-v1.22.0.tgz
    version: v1.22.0
  - apiVersion: v1
    appVersion: v1.21.0
    created: "2023-10-18T11:06:10.903804942Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 50a5c0860aa631c7e83affbaeac1a84c43c96b19175e1dd1c21cba472564798d
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.21.0/azuredisk-csi-driver-v1.21.0.tgz
    version: v1.21.0
  - apiVersion: v1
    appVersion: v1.20.0
    created: "2023-10-18T11:06:10.902838188Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 9f2a936be5efc45002c12d5bbbd8cb453e51a0c1668f6ceae51df656ac190c95
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.20.0/azuredisk-csi-driver-v1.20.0.tgz
    version: v1.20.0
  - apiVersion: v1
    appVersion: v1.19.0
    created: "2023-10-18T11:06:10.901378618Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 6c044a33b4adf598b9810e8839f04a16b1214470eceeb61bbe48076552955296
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.19.0/azuredisk-csi-driver-v1.19.0.tgz
    version: v1.19.0
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2023-10-18T11:06:10.900403851Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 79474616c7373ed65bbf75050748fda16ae2f6b290d240813006abd74e733628
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.18.0/azuredisk-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2023-10-18T11:06:10.899450935Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: dcaad8438f57941c19f2269d9d4510591529f4de00353d12506fd277dc06378e
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.17.0/azuredisk-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2023-10-18T11:06:10.898091958Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 95108dce3a4da8aad2729ff8bc1587906b917925e6fe2e5935b5d25805080fb4
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.16.0/azuredisk-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2023-10-18T11:06:10.896546899Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 3da85b9206af81dc4217a3304bf14839158112300de7dbb95841e30daaf5e4e5
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.15.0/azuredisk-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2023-10-18T11:06:10.895615776Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 89e87dead7767f8abd56096e436956b23a666802040f7aad91d5b6c36af8b098
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.14.0/azuredisk-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2023-10-18T11:06:10.894638538Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: c109533218e0625e9ca33c2db5e73c4b550b88943f7950b33e02a344a8ff9f8c
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.13.0/azuredisk-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2023-10-18T11:06:10.893721157Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: e41f089e5216fc9263039310990d1e41bcb468a85879289af1834dea0c457aaa
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.12.0/azuredisk-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2023-10-18T11:06:10.892793801Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: f35447c256488b1942342e9fcf8b6bed5f47b4ae5fb0fdae037110c5926803fe
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.11.0/azuredisk-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2023-10-18T11:06:10.891791335Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 12bd0e1f20a2e2adcb04b6954423438d9ece7a2ad0fb4b4fe2969844d14cfb86
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.10.0/azuredisk-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: v1.9.0
    created: "2023-10-18T11:06:10.926164916Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: d917427661ca4ec13add77efcfe31d2c7c989e20b1427dd566a05ad1bdd98fa9
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.9.0/azuredisk-csi-driver-v1.9.0.tgz
    version: v1.9.0
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2023-10-18T11:06:10.925164635Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: a37491e845671e81b9567f2d1a746dbf4f182fde0c8f9e689dfa632c5651c6c9
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.8.0/azuredisk-csi-driver-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.7.0
    created: "2023-10-18T11:06:10.924327694Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 4df7a10466206c60deab00efbca57f67f042afd1ecd5daca738df28526f3ffcc
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.7.0/azuredisk-csi-driver-v1.7.0.tgz
    version: v1.7.0
  - apiVersion: v1
    appVersion: v1.6.0
    created: "2023-10-18T11:06:10.923582485Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: b1a4c384fdfdb6577dd6dfd3709fb746b5c79247846e5c582b93c3a1187f6d88
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.6.0/azuredisk-csi-driver-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.1
    created: "2023-10-18T11:06:10.922078968Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: efb42e1d56cc5596eb4e695b658c2748bc05cc6c47862e3f20ea6b5b199d01d6
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.5.1/azuredisk-csi-driver-v1.5.1.tgz
    version: v1.5.1
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2023-10-18T11:06:10.921375332Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: c8490efde8d4a43bd25f5c619887498dfb4b41edf3929ac8dbf0a9d3f691e6ae
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.5.0/azuredisk-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2023-10-18T11:06:10.920642299Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 55e5e17aac7c144b21a198867654ef70ad272987b0bb165782905adf91ca3c03
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.4.0/azuredisk-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2023-10-18T11:06:10.919990267Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 2665483e922a577feb8539ca7f774bc70c945ce490294fd3378f098c2d244dde
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.3.0/azuredisk-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2023-10-18T11:06:10.901882154Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 2bbfe2f9d080f1b3ff10590c7168d05ce026c5a73332b4d48014610a52337808
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.2.0/azuredisk-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.1
    created: "2023-10-18T11:06:10.889803388Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: dd7066be8f499f6c1a396ab27c0013c09f5a8d8319cc04fbdd480d31107bb851
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.1.1/azuredisk-csi-driver-v1.1.1.tgz
    version: v1.1.1
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2023-10-18T11:06:10.889300745Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 3d2a5189416dd6a43bd3e2097bbe23a8db347b6e1a36c6a43fd59cc9c9633ff3
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.1.0/azuredisk-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2023-10-18T11:06:10.888732443Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: d179bc6f338518859b6efdc3b3bed8d06513313e8047563eb4b654b2d417c81e
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.0.0/azuredisk-csi-driver-v1.0.0.tgz
    version: v1.0.0
generated: "2023-10-18T11:06:10.885291819Z"
